version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    enviroments:
      POSTGRESQL_USERNAME=docker
      POSTGRESQL_PASSWORD=docker
      POSTGRESQL_DATABASE=apisolid
